[project]
name = "ict-facekit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.12"
dependencies = [
	"numpy>=1.26",
	"trimesh>=4.0.0",
	"pyrender>=0.1.45",
	"matplotlib>=3.5.0",
	"imageio>=2.31.0",
	"imageio-ffmpeg>=0.4.9",
]
